### ISSUE TITLE
SQS does not reload on changes

### ISSUE THREAD

**Issue by Limess** [godu/serverless#12]
This plugin is working great on first start, however when the function which is subscribing to the change is changed, and `serverless-offline` triggers a restart, the SQS subscription no longer seems to work.

Here's my config for reference:

```yaml
plugins:
  - serverless-webpack
  - serverless-log-forwarding
  - serverless-offline-sqs
  - serverless-offline

custom:
  serverless-offline-sqs:
    endpoint: http://0.0.0.0:9324
    region: ${self:provider.region}
    accessKeyId: local
    secretAccessKey: local

  serverless-offline:
    # httpsProtocol: certs
    dontPrintOutput: true
    host: local.in.ft.com
    port: ${env:PORT, '3000'}
    noTimeout: true

functions:
  releaseLogConsumer:
    handler: src/handlers/release-log-consumer.handler
    events:
      - sqs:
          arn:
            Fn::GetAtt:
              - ReleaseLogQueue
              - Arn
          batchSize: 10

resources:
  Resources:
    # Release Log resources
    ReleaseLogQueue:
      Type: "AWS::SQS::Queue"
      Properties:
        QueueName: "${self:custom.releaseLogQueueName}"
        RedrivePolicy:
          deadLetterTargetArn:
            Fn::GetAtt:
              - ReleaseLogDeadLetterQueue
              - Arn
          maxReceiveCount: 5
        MessageRetentionPeriod: 345600 # 4 days
        VisibilityTimeout: 25
        KmsMasterKeyId: alias/aws/sqs
```
